### ISSUE TITLE
ps4/extension/elfloader.h not in libps4

### ISSUE THREAD

**Issue by segobi** [psxdev/ps4link#1]
file is missing. Also libelfldr is not being compiled / nowhere to be found.

**Comment by psxdev** [comment]
Yes, it is not on libps4 yet. You can copy elfloader.h from elfldr repository it is at elfldr/ps4/include and you can generate elfloader.a (its only elfloader.o inside, check issue in elfldr repository i am speaking with hitodama about it) from there. I renamed it to libelfloader.a and copy to libps4/lib

**Comment by segobi** [comment]
thanks! I got it to compile.

**Comment by hitodama** [comment]
Sorry bout that, I will add it later today to libps4 and port the elfloader repo to the (shared) libps4 file sometime later (weekend).

**Comment by hitodama** [comment]
Hey, sorry I took longer https://github.com/ps4dev/libps4/commit/bd512026924a707911974f366cea5d0882e78c9d
I added elfloader.c too. I don't really like it, because I want the "elfldr" project to be self-contained but for now I will keep the two files in sync I think.

**Comment by hitodama** [comment]
This should be resolved, no?

**Comment by psxdev** [comment]
yes closing it
