### ISSUE TITLE
Can be port on Linux? 

### ISSUE THREAD

**Issue by genhack** [psxdev/ps4link#14]
Hello i try to install it on linux i follow the instruction in readame but when i do 

> cmake --build . --target install
i have 
`root@localhost-002:~/Scrivania/crossllvm/build# cmake --build . --target install
[  0%] Built target LLVMDemangle
[  4%] Built target LLVMSupport
[  4%] Built target LLVMTableGen
[  6%] Built target obj.llvm-tblgen
[  6%] Built target llvm-tblgen
[  7%] Built target AttributeCompatFuncTableGen
[  7%] Built target intrinsics_gen
[  9%] Built target LLVMCore
[  9%] Built target LLVMIRReader
[  9%] Building CXX object lib/CodeGen/CMakeFiles/LLVMCodeGen.dir/LexicalScopes.cpp.o
In file included from /root/Scrivania/crossllvm/llvm/lib/CodeGen/LexicalScopes.cpp:17:
In file included from /root/Scrivania/crossllvm/llvm/include/llvm/CodeGen/LexicalScopes.h:20:
In file included from /root/Scrivania/crossllvm/llvm/include/llvm/ADT/ArrayRef.h:13:
In file included from /root/Scrivania/crossllvm/llvm/include/llvm/ADT/Hashing.h:49:
In file included from /root/Scrivania/crossllvm/llvm/include/llvm/Support/Host.h:17:
In file included from /root/Scrivania/crossllvm/llvm/include/llvm/ADT/StringMap.h:17:
In file included from /root/Scrivania/crossllvm/llvm/include/llvm/ADT/StringRef.h:13:
In file included from /root/Scrivania/crossllvm/llvm/include/llvm/ADT/STLExtras.h:24:
In file included from /usr/bin/../lib/gcc/x86_64-linux-gnu/6.2.1/../../../../include/c++/6.2.1/functional:55:
/usr/bin/../lib/gcc/x86_64-linux-gnu/6.2.1/../../../../include/c++/6.2.1/tuple:1400:14: error: no matching constructor for initialization of
      'tuple<llvm::LexicalScope *&&, const llvm::DILocalScope *&&, nullptr_t &&, bool &&>'
    { return tuple<_Elements&&...>(std::forward<_Elements>(__args)...); }
             ^                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/root/Scrivania/crossllvm/llvm/lib/CodeGen/LexicalScopes.cpp:155:36: note: in instantiation of function template specialization
      'std::forward_as_tuple<llvm::LexicalScope *&, const llvm::DILocalScope *&, nullptr_t, bool>' requested here
                              std::forward_as_tuple(Parent, Scope, nullptr,
                                   ^
/usr/bin/../lib/gcc/x86_64-linux-gnu/6.2.1/../../../../include/c++/6.2.1/tuple:600:18: note: candidate template ignored: disabled by 'enable_if'
      [with _Dummy = void]
                 _TCC<_Dummy>::template
                 ^
/usr/bin/../lib/gcc/x86_64-linux-gnu/6.2.1/../../../../include/c++/6.2.1/tuple:611:18: note: candidate template ignored: disabled by 'enable_if'
      [with _Dummy = void]
                 _TCC<_Dummy>::template
                 ^
/usr/bin/../lib/gcc/x86_64-linux-gnu/6.2.1/../../../../include/c++/6.2.1/tuple:628:5: note: candidate template ignored: disabled by 'enable_if'
      [with _UElements = <llvm::LexicalScope *&, const llvm::DILocalScope *&, nullptr_t, bool>]
                  _TC<sizeof...(_UElements) == 1, _Elements...>::template
                  ^
/usr/bin/../lib/gcc/x86_64-linux-gnu/6.2.1/../../../../include/c++/6.2.1/tuple:641:5: note: candidate template ignored: disabled by 'enable_if'
      [with _UElements = <llvm::LexicalScope *&, const llvm::DILocalScope *&, nullptr_t, bool>]
                  _TC<sizeof...(_UElements) == 1, _Elements...>::template
                  ^
/usr/bin/../lib/gcc/x86_64-linux-gnu/6.2.1/../../../../include/c++/6.2.1/tuple:737:19: note: candidate template ignored: disabled by 'enable_if'
      [with _Alloc = const llvm::DILocalScope *, _UElements = <nullptr_t, bool>]
        enable_if<_TMC<_UElements...>::template
                  ^
/usr/bin/../lib/gcc/x86_64-linux-gnu/6.2.1/../../../../include/c++/6.2.1/tuple:748:19: note: candidate template ignored: disabled by 'enable_if'
      [with _Alloc = const llvm::DILocalScope *, _UElements = <nullptr_t, bool>]
        enable_if<_TMC<_UElements...>::template
                  ^
/usr/bin/../lib/gcc/x86_64-linux-gnu/6.2.1/../../../../include/c++/6.2.1/tuple:579:17: note: candidate constructor template not viable: requires
      0 arguments, but 4 were provided
      constexpr tuple()
                ^
/usr/bin/../lib/gcc/x86_64-linux-gnu/6.2.1/../../../../include/c++/6.2.1/tuple:589:26: note: candidate constructor template not viable: requires
      0 arguments, but 4 were provided
      explicit constexpr tuple()
                         ^
/usr/bin/../lib/gcc/x86_64-linux-gnu/6.2.1/../../../../include/c++/6.2.1/tuple:670:19: note: candidate constructor template not viable: requires
      single argument '__in', but 4 arguments were provided
        constexpr tuple(const tuple<_UElements...>& __in)
                  ^
/usr/bin/../lib/gcc/x86_64-linux-gnu/6.2.1/../../../../include/c++/6.2.1/tuple:682:28: note: candidate constructor template not viable: requires
      single argument '__in', but 4 arguments were provided
        explicit constexpr tuple(const tuple<_UElements...>& __in)
                           ^
/usr/bin/../lib/gcc/x86_64-linux-gnu/6.2.1/../../../../include/c++/6.2.1/tuple:694:19: note: candidate constructor template not viable: requires
      single argument '__in', but 4 arguments were provided
        constexpr tuple(tuple<_UElements...>&& __in)
                  ^
/usr/bin/../lib/gcc/x86_64-linux-gnu/6.2.1/../../../../include/c++/6.2.1/tuple:705:28: note: candidate constructor template not viable: requires
      single argument '__in', but 4 arguments were provided
        explicit constexpr tuple(tuple<_UElements...>&& __in)
                           ^
/usr/bin/../lib/gcc/x86_64-linux-gnu/6.2.1/../../../../include/c++/6.2.1/tuple:721:2: note: candidate constructor template not viable: requires
      6 arguments, but 4 were provided
        tuple(allocator_arg_t __tag, const _Alloc& __a,
        ^
/usr/bin/../lib/gcc/x86_64-linux-gnu/6.2.1/../../../../include/c++/6.2.1/tuple:732:11: note: candidate constructor template not viable: requires
      6 arguments, but 4 were provided
        explicit tuple(allocator_arg_t __tag, const _Alloc& __a,
                 ^
/usr/bin/../lib/gcc/x86_64-linux-gnu/6.2.1/../../../../include/c++/6.2.1/tuple:711:2: note: candidate constructor template not viable: requires
      2 arguments, but 4 were provided
        tuple(allocator_arg_t __tag, const _Alloc& __a)
        ^
/usr/bin/../lib/gcc/x86_64-linux-gnu/6.2.1/../../../../include/c++/6.2.1/tuple:759:2: note: candidate constructor template not viable: requires
      3 arguments, but 4 were provided
        tuple(allocator_arg_t __tag, const _Alloc& __a, const tuple& __in)
        ^
/usr/bin/../lib/gcc/x86_64-linux-gnu/6.2.1/../../../../include/c++/6.2.1/tuple:763:2: note: candidate constructor template not viable: requires
      3 arguments, but 4 were provided
        tuple(allocator_arg_t __tag, const _Alloc& __a, tuple&& __in)
        ^
/usr/bin/../lib/gcc/x86_64-linux-gnu/6.2.1/../../../../include/c++/6.2.1/tuple:772:2: note: candidate constructor template not viable: requires
      3 arguments, but 4 were provided
        tuple(allocator_arg_t __tag, const _Alloc& __a,
        ^
/usr/bin/../lib/gcc/x86_64-linux-gnu/6.2.1/../../../../include/c++/6.2.1/tuple:784:11: note: candidate constructor template not viable: requires
      3 arguments, but 4 were provided
        explicit tuple(allocator_arg_t __tag, const _Alloc& __a,
                 ^
/usr/bin/../lib/gcc/x86_64-linux-gnu/6.2.1/../../../../include/c++/6.2.1/tuple:796:2: note: candidate constructor template not viable: requires
      3 arguments, but 4 were provided
        tuple(allocator_arg_t __tag, const _Alloc& __a,
        ^
/usr/bin/../lib/gcc/x86_64-linux-gnu/6.2.1/../../../../include/c++/6.2.1/tuple:808:11: note: candidate constructor template not viable: requires
      3 arguments, but 4 were provided
        explicit tuple(allocator_arg_t __tag, const _Alloc& __a,
                 ^
/usr/bin/../lib/gcc/x86_64-linux-gnu/6.2.1/../../../../include/c++/6.2.1/tuple:654:17: note: candidate constructor not viable: requires 1
      argument, but 4 were provided
      constexpr tuple(tuple&&) = default; 
                ^
/usr/bin/../lib/gcc/x86_64-linux-gnu/6.2.1/../../../../include/c++/6.2.1/tuple:652:17: note: candidate constructor not viable: requires 1
      argument, but 4 were provided
      constexpr tuple(const tuple&) = default;
                ^
/usr/bin/../lib/gcc/x86_64-linux-gnu/6.2.1/../../../../include/c++/6.2.1/tuple:1400:14: error: no matching constructor for initialization of
      'tuple<llvm::LexicalScope *&&, const llvm::DILocalScope *&&, const llvm::DILocation *&&, bool &&>'
    { return tuple<_Elements&&...>(std::forward<_Elements>(__args)...); }
             ^                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/root/Scrivania/crossllvm/llvm/lib/CodeGen/LexicalScopes.cpp:186:43: note: in instantiation of function template specialization
      'std::forward_as_tuple<llvm::LexicalScope *&, const llvm::DILocalScope *&, const llvm::DILocation *&, bool>' requested here
                                     std::forward_as_tuple(Parent, Scope,
                                          ^
/usr/bin/../lib/gcc/x86_64-linux-gnu/6.2.1/../../../../include/c++/6.2.1/tuple:600:18: note: candidate template ignored: disabled by 'enable_if'
      [with _Dummy = void]
                 _TCC<_Dummy>::template
                 ^
/usr/bin/../lib/gcc/x86_64-linux-gnu/6.2.1/../../../../include/c++/6.2.1/tuple:611:18: note: candidate template ignored: disabled by 'enable_if'
      [with _Dummy = void]
                 _TCC<_Dummy>::template
                 ^
/usr/bin/../lib/gcc/x86_64-linux-gnu/6.2.1/../../../../include/c++/6.2.1/tuple:628:5: note: candidate template ignored: disabled by 'enable_if'
      [with _UElements = <llvm::LexicalScope *&, const llvm::DILocalScope *&, const llvm::DILocation *&, bool>]
                  _TC<sizeof...(_UElements) == 1, _Elements...>::template
                  ^
/usr/bin/../lib/gcc/x86_64-linux-gnu/6.2.1/../../../../include/c++/6.2.1/tuple:641:5: note: candidate template ignored: disabled by 'enable_if'
      [with _UElements = <llvm::LexicalScope *&, const llvm::DILocalScope *&, const llvm::DILocation *&, bool>]
                  _TC<sizeof...(_UElements) == 1, _Elements...>::template
                  ^
/usr/bin/../lib/gcc/x86_64-linux-gnu/6.2.1/../../../../include/c++/6.2.1/tuple:737:19: note: candidate template ignored: disabled by 'enable_if'
      [with _Alloc = const llvm::DILocalScope *, _UElements = <const llvm::DILocation *&, bool>]
        enable_if<_TMC<_UElements...>::template
                  ^
/usr/bin/../lib/gcc/x86_64-linux-gnu/6.2.1/../../../../include/c++/6.2.1/tuple:748:19: note: candidate template ignored: disabled by 'enable_if'
      [with _Alloc = const llvm::DILocalScope *, _UElements = <const llvm::DILocation *&, bool>]
        enable_if<_TMC<_UElements...>::template
                  ^
/usr/bin/../lib/gcc/x86_64-linux-gnu/6.2.1/../../../../include/c++/6.2.1/tuple:579:17: note: candidate constructor template not viable: requires
      0 arguments, but 4 were provided
      constexpr tuple()
                ^
/usr/bin/../lib/gcc/x86_64-linux-gnu/6.2.1/../../../../include/c++/6.2.1/tuple:589:26: note: candidate constructor template not viable: requires
      0 arguments, but 4 were provided
      explicit constexpr tuple()
                         ^
/usr/bin/../lib/gcc/x86_64-linux-gnu/6.2.1/../../../../include/c++/6.2.1/tuple:670:19: note: candidate constructor template not viable: requires
      single argument '__in', but 4 arguments were provided
        constexpr tuple(const tuple<_UElements...>& __in)
                  ^
/usr/bin/../lib/gcc/x86_64-linux-gnu/6.2.1/../../../../include/c++/6.2.1/tuple:682:28: note: candidate constructor template not viable: requires
      single argument '__in', but 4 arguments were provided
        explicit constexpr tuple(const tuple<_UElements...>& __in)
                           ^
/usr/bin/../lib/gcc/x86_64-linux-gnu/6.2.1/../../../../include/c++/6.2.1/tuple:694:19: note: candidate constructor template not viable: requires
      single argument '__in', but 4 arguments were provided
        constexpr tuple(tuple<_UElements...>&& __in)
                  ^
/usr/bin/../lib/gcc/x86_64-linux-gnu/6.2.1/../../../../include/c++/6.2.1/tuple:705:28: note: candidate constructor template not viable: requires
      single argument '__in', but 4 arguments were provided
        explicit constexpr tuple(tuple<_UElements...>&& __in)
                           ^
/usr/bin/../lib/gcc/x86_64-linux-gnu/6.2.1/../../../../include/c++/6.2.1/tuple:721:2: note: candidate constructor template not viable: requires
      6 arguments, but 4 were provided
        tuple(allocator_arg_t __tag, const _Alloc& __a,
        ^
/usr/bin/../lib/gcc/x86_64-linux-gnu/6.2.1/../../../../include/c++/6.2.1/tuple:732:11: note: candidate constructor template not viable: requires
      6 arguments, but 4 were provided
        explicit tuple(allocator_arg_t __tag, const _Alloc& __a,
                 ^
/usr/bin/../lib/gcc/x86_64-linux-gnu/6.2.1/../../../../include/c++/6.2.1/tuple:711:2: note: candidate constructor template not viable: requires
      2 arguments, but 4 were provided
        tuple(allocator_arg_t __tag, const _Alloc& __a)
        ^
/usr/bin/../lib/gcc/x86_64-linux-gnu/6.2.1/../../../../include/c++/6.2.1/tuple:759:2: note: candidate constructor template not viable: requires
      3 arguments, but 4 were provided
        tuple(allocator_arg_t __tag, const _Alloc& __a, const tuple& __in)
        ^
/usr/bin/../lib/gcc/x86_64-linux-gnu/6.2.1/../../../../include/c++/6.2.1/tuple:763:2: note: candidate constructor template not viable: requires
      3 arguments, but 4 were provided
        tuple(allocator_arg_t __tag, const _Alloc& __a, tuple&& __in)
        ^
/usr/bin/../lib/gcc/x86_64-linux-gnu/6.2.1/../../../../include/c++/6.2.1/tuple:772:2: note: candidate constructor template not viable: requires
      3 arguments, but 4 were provided
        tuple(allocator_arg_t __tag, const _Alloc& __a,
        ^
/usr/bin/../lib/gcc/x86_64-linux-gnu/6.2.1/../../../../include/c++/6.2.1/tuple:784:11: note: candidate constructor template not viable: requires
      3 arguments, but 4 were provided
        explicit tuple(allocator_arg_t __tag, const _Alloc& __a,
                 ^
/usr/bin/../lib/gcc/x86_64-linux-gnu/6.2.1/../../../../include/c++/6.2.1/tuple:796:2: note: candidate constructor template not viable: requires
      3 arguments, but 4 were provided
        tuple(allocator_arg_t __tag, const _Alloc& __a,
        ^
/usr/bin/../lib/gcc/x86_64-linux-gnu/6.2.1/../../../../include/c++/6.2.1/tuple:808:11: note: candidate constructor template not viable: requires
      3 arguments, but 4 were provided
        explicit tuple(allocator_arg_t __tag, const _Alloc& __a,
                 ^
/usr/bin/../lib/gcc/x86_64-linux-gnu/6.2.1/../../../../include/c++/6.2.1/tuple:654:17: note: candidate constructor not viable: requires 1
      argument, but 4 were provided
      constexpr tuple(tuple&&) = default; 
                ^
/usr/bin/../lib/gcc/x86_64-linux-gnu/6.2.1/../../../../include/c++/6.2.1/tuple:652:17: note: candidate constructor not viable: requires 1
      argument, but 4 were provided
      constexpr tuple(const tuple&) = default;
                ^
/root/Scrivania/crossllvm/llvm/lib/CodeGen/LexicalScopes.cpp:208:32: error: no matching function for call to 'forward_as_tuple'
                               std::forward_as_tuple(Parent, Scope,
                               ^~~~~~~~~~~~~~~~~~~~~
/usr/bin/../lib/gcc/x86_64-linux-gnu/6.2.1/../../../../include/c++/6.2.1/tuple:1399:5: note: candidate template ignored: substitution failure
      [with _Elements = <llvm::LexicalScope *&, const llvm::DILocalScope *&, nullptr_t, bool>]
    forward_as_tuple(_Elements&&... __args) noexcept
    ^
3 errors generated.
lib/CodeGen/CMakeFiles/LLVMCodeGen.dir/build.make:974: set di istruzioni per l'obiettivo "lib/CodeGen/CMakeFiles/LLVMCodeGen.dir/LexicalScopes.cpp.o" non riuscito
make[2]: *** [lib/CodeGen/CMakeFiles/LLVMCodeGen.dir/LexicalScopes.cpp.o] Errore 1
CMakeFiles/Makefile2:1145: set di istruzioni per l'obiettivo "lib/CodeGen/CMakeFiles/LLVMCodeGen.dir/all" non riuscito
make[1]: *** [lib/CodeGen/CMakeFiles/LLVMCodeGen.dir/all] Errore 2
Makefile:149: set di istruzioni per l'obiettivo "all" non riuscito
make: *** [all] Errore 2
root@localhost-002:~/Scrivania/crossllvm/build# 
`

Any solutions? thanks in advance!

**Comment by psxdev** [comment]
If you see : 
cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr/local/ps4dev/toolchain -DLLVM_ENABLE_ASSERTIONS=ON -DLLVM_DEFAULT_TARGET_TRIPLE=x86_64-scei-ps4 -**DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++** -DCOMPILER_RT_BUILD_BUILTINS:BOOL=OFF -DCOMPILER_RT_BUILD_SANITIZERS:BOOL=OFF -DCOMPILER_RT_CAN_EXECUTE_TESTS:BOOL=OFF -DCOMPILER_RT_INCLUDE_TESTS:BOOL=OFF -DLLVM_TOOL_COMPILER_RT_BUILD:BOOL=OFF  -DCLANG_BUILD_EXAMPLES:BOOL=ON -DLLVM_TARGETS_TO_BUILD=X86 -DCMAKE_C_FLAGS="-Wdocumentation -Wno-documentation-deprecated-sync" -DCMAKE_CXX_FLAGS="-std=c++11 -Wdocumentation -Wno-documentation-deprecated-sync" -DLLVM_LIT_ARGS="-v" ../llvm

It is using clang and clang++ like native compiler. In OS X clang is native compiler in Linux does not, so change to gcc and g++
