### ISSUE TITLE
ps4sdk not building

### ISSUE THREAD

**Issue by gut5** [psxdev/ps4link#15]
sorry to contact you on this repo instead of the ps4sdk but you didn't have issues enabled there. the 5.05 tree of the ps4sdk won't build on Ubuntu Linux, I have got clang 6.0 and cmake (and normal make) installed, and I'm running make in the directory and getting this error
```

~/ps4/ps4sdk-firmware505$ make       
make -C base all 
make[1]: Entering directory '/home/user/ps4/ps4sdk-firmware505/base'
Makefile:9: *** Neither PS4SDK, Ps4Sdk nor ps4sdk set. Stop.
make[1]: Leaving directory '/home/user/ps4/ps4sdk-firmware505/base'
Makefile:4: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by psxdev** [comment]
check readme
change properly to your config
cd ps4sdk
PS4SDK=/usr/local/orbisdev/git/ps4sdk;export PS4SDK
make

**Comment by gut5** [comment]
Thanks, it's building now, all it needed was the environment variable.
