### ISSUE TITLE
PS4SH doens't want to launch the elf (fMSX)

### ISSUE THREAD

**Issue by ghost** [psxdev/ps4link#16]
Hi !
I have a problem with the PS4SH, i have compiled with success fMSX and i have add all file needed (Game + BIOS/Filesystem). i have renamed it "homebrew.elf" and i have launched OrbisLink.

But i can't launch the .elf (nothing in the screen just the OrbisLink logo)

Screenshot: 

![fmsx data](https://user-images.githubusercontent.com/20625892/42290269-82e929aa-7fc4-11e8-9ff4-1e6f0a579092.png)

**Comment by psxdev** [comment]
Open ps4sh
Load orbislink
Check logs 
connect

**Comment by ghost** [comment]
I doesn't recevie any log from the ps4 (i have launched ps4sh before with root perm.)
And i can launch another homebrew without problem

**Comment by psxdev** [comment]
For fmsx you need enable fmsx flag in media/config.ini in the pkg

Check https://gist.github.com/psxdev/132ac158dadb37844d87d6b0ac3cb303
initOrbisLinkApp Method 

Fmsx need mono configuration for audio,so i put a flag in config.ini to use its custom audio config

Also change ip of your pc in config.ini to receive logs in ps4sh

**Comment by psxdev** [comment]
@theorywrong did you try it? Can i close the issue?

**Comment by ghost** [comment]
Yes, thanks !

**Comment by pquerner** [comment]
How can I alter data in media/config.ini in a packaged .pkg ?
I think I have the same issue, as ps4link tries to a invalid ip address in my network. How can I change that?

*edit* I changed my network settings, and now my serverip is also 192.168.1.3, because I couldnt figure out how to change the serverip.
