### ISSUE TITLE
linker error

### ISSUE THREAD

**Issue by eth-man** [psxdev/ps4link#3]
ps4link and elfldr is not complied 
same error on freebsd and os x:

sh-3.2# make
clang /usr/local/ps4dev/libps4/crt0.s build/main.o  -O3 -Wall -m64 -nostdlib -L/usr/local/ps4dev/libps4/lib  -pie -ldebugnet -lps4link -lelfloader -lps4    -o bin/ps4link.elf
clang: warning: argument unused during compilation: '-pie'
/usr/local/ps4dev/libps4/crt0.s:1:19: error: unexpected token in '.section' directive
.pushsection .text
                  ^
/usr/local/ps4dev/libps4/crt0.s:3:1: error: unknown directive
.type _start, @function
^
/usr/local/ps4dev/libps4/crt0.s:6:1: error: unknown directive
.size _start, .-_start
^
/usr/local/ps4dev/libps4/crt0.s:7:12: error: .popsection without corresponding .pushsection
.popsection
           ^
make: **\* [ps4link] Error 1

**Comment by psxdev** [comment]
are you sure that you are using clang >= 3.7 you can't use native osx clang with this

**Comment by fx0day** [comment]
i had the same issue : 

You're using clang from Xcode 

Try a clang -v , if you get this it's not good !!!

Apple LLVM version 7.3.0 (clang-703.0.29)
Target: x86_64-apple-darwin15.4.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

You should see this : 

 clang -v
clang version 3.9.0 (http://llvm.org/git/clang.git 3ec937288f3d932d2b480638123f5214c5575e8b) (http://llvm.org/git/llvm.git 8674e1c5a332d22cb0486d7737af3f0e2e46fa4b)
Target: x86_64-scei-ps4
Thread model: posix
InstalledDir: /usr/local/ps4dev//toolchain/bin

**Comment by eth-man** [comment]
yes i was using the export variable with the wrong order
what stupid mistake by me :)
thanks!
