### ISSUE TITLE
Error linking elfldf and ps4link (multiple definitions)

### ISSUE THREAD

**Issue by ghost** [psxdev/ps4link#4]
I am encountering linker errors while linking due to duplicate symbols. Any idea ? Is there a way to check the exported symbols in the static library ?

Elfldr

clang  /usr/local/ps4dev/libps4/crt0.s  build/commands.c.o  build/debugnet.c.o  build/elfloader.c.o  build/main.c.o  build/ps4link.c.o  build/requests.c.o  -O3 -Wall -m64 -L. -Llib  -nostdlib -L/usr/local/ps4dev/libps4/lib -Wl,-Ttext,0x93a300000 -Wl,-Tdata,0x93a400000  -lps4 -o bin/ldr
/usr/local/ps4dev/libps4/lib/libps4.a(elfloader.c.o): In function `elfAddendRelocationAttribute':
source/ps4/elfloader.c:(.text+0xcb0): multiple definition of`elfAddendRelocationAttribute'
build/elfloader.c.o:source/elfloader.c:(.text+0xab0): first defined here
/usr/local/ps4dev/libps4/lib/libps4.a(elfloader.c.o): In function `elfAddendRelocations':
source/ps4/elfloader.c:(.text+0xcd0): multiple definition of`elfAddendRelocations'
build/elfloader.c.o:source/elfloader.c:(.text+0xad0): first defined here
/usr/local/ps4dev/libps4/lib/libps4.a(elfloader.c.o): In function `elfCreate':
source/ps4/elfloader.c:(.text+0xf40): multiple definition of`elfCreate'
build/elfloader.c.o:source/elfloader.c:(.text+0xd40): first defined here
/usr/local/ps4dev/libps4/lib/libps4.a(elfloader.c.o): In function `elfDestroy':
source/ps4/elfloader.c:(.text+0xfd0): multiple definition of`elfDestroy'
build/elfloader.c.o:source/elfloader.c:(.text+0xe00): first defined here
/usr/local/ps4dev/libps4/lib/libps4.a(elfloader.c.o): In function `elfDestroyAndFree':
source/ps4/elfloader.c:(.text+0x1000): multiple definition of`elfDestroyAndFree'
build/elfloader.c.o:source/elfloader.c:(.text+0xe20): first defined here
/usr/local/ps4dev/libps4/lib/libps4.a(elfloader.c.o): In function `elfDynamic':
source/ps4/elfloader.c:(.text+0x860): multiple definition of`elfDynamic'
build/elfloader.c.o:source/elfloader.c:(.text+0x7f0): first defined here
/usr/local/ps4dev/libps4/lib/libps4.a(elfloader.c.o): In function `elfDynamicAttribute':
source/ps4/elfloader.c:(.text+0x6d0): multiple definition of`elfDynamicAttribute'
build/elfloader.c.o:source/elfloader.c:(.text+0x6e0): first defined here
/usr/local/ps4dev/libps4/lib/libps4.a(elfloader.c.o): In function `elfDynamics':
source/ps4/elfloader.c:(.text+0x730): multiple definition of`elfDynamics'
build/elfloader.c.o:source/elfloader.c:(.text+0x700): first defined here
/usr/local/ps4dev/libps4/lib/libps4.a(elfloader.c.o): In function `elfEntry':
source/ps4/elfloader.c:(.text+0x10): multiple definition of`elfEntry'
build/elfloader.c.o:source/elfloader.c:(.text+0x10): first defined here
/usr/local/ps4dev/libps4/lib/libps4.a(elfloader.c.o): In function `elfHeader':
source/ps4/elfloader.c:(.text+0x0): multiple definition of`elfHeader'
build/elfloader.c.o:source/elfloader.c:(.text+0x0): first defined here
/usr/local/ps4dev/libps4/lib/libps4.a(elfloader.c.o): In function `elfLargestAlignment':
source/ps4/elfloader.c:(.text+0x30): multiple definition of`elfLargestAlignment'
build/elfloader.c.o:source/elfloader.c:(.text+0x30): first defined here
/usr/local/ps4dev/libps4/lib/libps4.a(elfloader.c.o): In function `elfLoaderInstantiate':
source/ps4/elfloader.c:(.text+0x1100): multiple definition of`elfLoaderInstantiate'
build/elfloader.c.o:source/elfloader.c:(.text+0xf00): first defined here
/usr/local/ps4dev/libps4/lib/libps4.a(elfloader.c.o): In function `elfLoaderIsLoadable':
source/ps4/elfloader.c:(.text+0x1040): multiple definition of`elfLoaderIsLoadable'
build/elfloader.c.o:source/elfloader.c:(.text+0xe40): first defined here
/usr/local/ps4dev/libps4/lib/libps4.a(elfloader.c.o): In function `elfLoaderLoad':
source/ps4/elfloader.c:(.text+0x15d0): multiple definition of`elfLoaderLoad'
build/elfloader.c.o:source/elfloader.c:(.text+0x13b0): first defined here
/usr/local/ps4dev/libps4/lib/libps4.a(elfloader.c.o): In function `elfLoaderRelativeAddressIsExecutable':
source/ps4/elfloader.c:(.text+0x1250): multiple definition of`elfLoaderRelativeAddressIsExecutable'
build/elfloader.c.o:source/elfloader.c:(.text+0x1050): first defined here
/usr/local/ps4dev/libps4/lib/libps4.a(elfloader.c.o): In function `elfLoaderRelocate':
source/ps4/elfloader.c:(.text+0x1310): multiple definition of`elfLoaderRelocate'
build/elfloader.c.o:source/elfloader.c:(.text+0x1110): first defined here
/usr/local/ps4dev/libps4/lib/libps4.a(elfloader.c.o): In function `elfMemorySize':
source/ps4/elfloader.c:(.text+0x220): multiple definition of`elfMemorySize'
build/elfloader.c.o:source/elfloader.c:(.text+0x210): first defined here
/usr/local/ps4dev/libps4/lib/libps4.a(elfloader.c.o): In function `elfSection':
source/ps4/elfloader.c:(.text+0x3b0): multiple definition of`elfSection'
build/elfloader.c.o:source/elfloader.c:(.text+0x3c0): first defined here
/usr/local/ps4dev/libps4/lib/libps4.a(elfloader.c.o): In function `elfSectionAttribute':
source/ps4/elfloader.c:(.text+0x520): multiple definition of`elfSectionAttribute'
build/elfloader.c.o:source/elfloader.c:(.text+0x530): first defined here
/usr/local/ps4dev/libps4/lib/libps4.a(elfloader.c.o): In function `elfSectionByName':
source/ps4/elfloader.c:(.text+0x570): multiple definition of`elfSectionByName'
build/elfloader.c.o:source/elfloader.c:(.text+0x580): first defined here
/usr/local/ps4dev/libps4/lib/libps4.a(elfloader.c.o): In function `elfSectionStrings':
source/ps4/elfloader.c:(.text+0x350): multiple definition of`elfSectionStrings'
build/elfloader.c.o:source/elfloader.c:(.text+0x360): first defined here
/usr/local/ps4dev/libps4/lib/libps4.a(elfloader.c.o): In function `elfSections':
source/ps4/elfloader.c:(.text+0x310): multiple definition of`elfSections'
build/elfloader.c.o:source/elfloader.c:(.text+0x320): first defined here
/usr/local/ps4dev/libps4/lib/libps4.a(elfloader.c.o): In function `elfSegment':
source/ps4/elfloader.c:(.text+0xc0): multiple definition of`elfSegment'
build/elfloader.c.o:source/elfloader.c:(.text+0xb0): first defined here
/usr/local/ps4dev/libps4/lib/libps4.a(elfloader.c.o): In function `elfSegmentAttribute':
source/ps4/elfloader.c:(.text+0x680): multiple definition of`elfSegmentAttribute'
build/elfloader.c.o:source/elfloader.c:(.text+0x690): first defined here
/usr/local/ps4dev/libps4/lib/libps4.a(elfloader.c.o): In function `elfSegments':
source/ps4/elfloader.c:(.text+0x2d0): multiple definition of`elfSegments'
build/elfloader.c.o:source/elfloader.c:(.text+0x2e0): first defined here
/usr/local/ps4dev/libps4/lib/libps4.a(elfloader.c.o): In function `elfStringFromIndex':
source/ps4/elfloader.c:(.text+0xbe0): multiple definition of`elfStringFromIndex'
build/elfloader.c.o:source/elfloader.c:(.text+0x9e0): first defined here
/usr/local/ps4dev/libps4/lib/libps4.a(elfloader.c.o): In function `elfStringFromOffset':
source/ps4/elfloader.c:(.text+0xc30): multiple definition of`elfStringFromOffset'
build/elfloader.c.o:source/elfloader.c:(.text+0xa30): first defined here
/usr/local/ps4dev/libps4/lib/libps4.a(elfloader.c.o): In function `elfStringToIndex':
source/ps4/elfloader.c:(.text+0xc50): multiple definition of`elfStringToIndex'
build/elfloader.c.o:source/elfloader.c:(.text+0xa50): first defined here
/usr/local/ps4dev/libps4/lib/libps4.a(elfloader.c.o): In function `elfStringToOffset':
source/ps4/elfloader.c:(.text+0x630): multiple definition of`elfStringToOffset'
build/elfloader.c.o:source/elfloader.c:(.text+0x640): first defined here
/usr/local/ps4dev/libps4/lib/libps4.a(elfloader.c.o): In function `elfSymbolAttribute':
source/ps4/elfloader.c:(.text+0xdf0): multiple definition of`elfSymbolAttribute'
build/elfloader.c.o:source/elfloader.c:(.text+0xbf0): first defined here
/usr/local/ps4dev/libps4/lib/libps4.a(elfloader.c.o): In function `elfSymbols':
source/ps4/elfloader.c:(.text+0xe30): multiple definition of`elfSymbols'
build/elfloader.c.o:source/elfloader.c:(.text+0xc30): first defined here
build/commands.c.o: In function `ps4LinkRunElf':
source/commands.c:(.text+0x187): undefined reference to`ps4ProtectedMemoryWritable'
source/commands.c:(.text+0x19f): undefined reference to `ps4ProtectedMemoryExecutable'
source/commands.c:(.text+0x1dc): undefined reference to`ps4ProtectedMemoryWritable'
clang-3.9: error: linker command failed with exit code 1 (use -v to see invocation)
make: **\* [bin/ldr] Error 1

Ps4Link

clang  /usr/local/ps4dev/libps4/crt0.s  build/main.c.o  -O3 -Wall -m64 -L. -Llib  -nostdlib -L/usr/local/ps4dev/libps4/lib -pie -ldebugnet -lps4link -lps4 -o bin/ps4link.elf
/usr/local/ps4dev/libps4/lib/libps4.a(elfloader.c.o): In function `elfAddendRelocationAttribute':
source/ps4/elfloader.c:(.text+0xcb0): multiple definition of`elfAddendRelocationAttribute'
/usr/local/ps4dev/libps4/lib/libps4link.a(elfloader.c.o):source/elfloader.c:(.text+0xab0): first defined here
/usr/local/ps4dev/libps4/lib/libps4.a(elfloader.c.o): In function `elfAddendRelocations':
source/ps4/elfloader.c:(.text+0xcd0): multiple definition of`elfAddendRelocations'
/usr/local/ps4dev/libps4/lib/libps4link.a(elfloader.c.o):source/elfloader.c:(.text+0xad0): first defined here
/usr/local/ps4dev/libps4/lib/libps4.a(elfloader.c.o): In function `elfCreate':
source/ps4/elfloader.c:(.text+0xf40): multiple definition of`elfCreate'
/usr/local/ps4dev/libps4/lib/libps4link.a(elfloader.c.o):source/elfloader.c:(.text+0xd40): first defined here
/usr/local/ps4dev/libps4/lib/libps4.a(elfloader.c.o): In function `elfDestroy':
source/ps4/elfloader.c:(.text+0xfd0): multiple definition of`elfDestroy'
/usr/local/ps4dev/libps4/lib/libps4link.a(elfloader.c.o):source/elfloader.c:(.text+0xe00): first defined here
/usr/local/ps4dev/libps4/lib/libps4.a(elfloader.c.o): In function `elfDestroyAndFree':
source/ps4/elfloader.c:(.text+0x1000): multiple definition of`elfDestroyAndFree'
/usr/local/ps4dev/libps4/lib/libps4link.a(elfloader.c.o):source/elfloader.c:(.text+0xe20): first defined here
/usr/local/ps4dev/libps4/lib/libps4.a(elfloader.c.o): In function `elfDynamic':
source/ps4/elfloader.c:(.text+0x860): multiple definition of`elfDynamic'
/usr/local/ps4dev/libps4/lib/libps4link.a(elfloader.c.o):source/elfloader.c:(.text+0x7f0): first defined here
/usr/local/ps4dev/libps4/lib/libps4.a(elfloader.c.o): In function `elfDynamicAttribute':
source/ps4/elfloader.c:(.text+0x6d0): multiple definition of`elfDynamicAttribute'
/usr/local/ps4dev/libps4/lib/libps4link.a(elfloader.c.o):source/elfloader.c:(.text+0x6e0): first defined here
/usr/local/ps4dev/libps4/lib/libps4.a(elfloader.c.o): In function `elfDynamics':
source/ps4/elfloader.c:(.text+0x730): multiple definition of`elfDynamics'
/usr/local/ps4dev/libps4/lib/libps4link.a(elfloader.c.o):source/elfloader.c:(.text+0x700): first defined here
/usr/local/ps4dev/libps4/lib/libps4.a(elfloader.c.o): In function `elfEntry':
source/ps4/elfloader.c:(.text+0x10): multiple definition of`elfEntry'
/usr/local/ps4dev/libps4/lib/libps4link.a(elfloader.c.o):source/elfloader.c:(.text+0x10): first defined here
/usr/local/ps4dev/libps4/lib/libps4.a(elfloader.c.o): In function `elfHeader':
source/ps4/elfloader.c:(.text+0x0): multiple definition of`elfHeader'
/usr/local/ps4dev/libps4/lib/libps4link.a(elfloader.c.o):source/elfloader.c:(.text+0x0): first defined here
/usr/local/ps4dev/libps4/lib/libps4.a(elfloader.c.o): In function `elfLargestAlignment':
source/ps4/elfloader.c:(.text+0x30): multiple definition of`elfLargestAlignment'
/usr/local/ps4dev/libps4/lib/libps4link.a(elfloader.c.o):source/elfloader.c:(.text+0x30): first defined here
/usr/local/ps4dev/libps4/lib/libps4.a(elfloader.c.o): In function `elfLoaderInstantiate':
source/ps4/elfloader.c:(.text+0x1100): multiple definition of`elfLoaderInstantiate'
/usr/local/ps4dev/libps4/lib/libps4link.a(elfloader.c.o):source/elfloader.c:(.text+0xf00): first defined here
/usr/local/ps4dev/libps4/lib/libps4.a(elfloader.c.o): In function `elfLoaderIsLoadable':
source/ps4/elfloader.c:(.text+0x1040): multiple definition of`elfLoaderIsLoadable'
/usr/local/ps4dev/libps4/lib/libps4link.a(elfloader.c.o):source/elfloader.c:(.text+0xe40): first defined here
/usr/local/ps4dev/libps4/lib/libps4.a(elfloader.c.o): In function `elfLoaderLoad':
source/ps4/elfloader.c:(.text+0x15d0): multiple definition of`elfLoaderLoad'
/usr/local/ps4dev/libps4/lib/libps4link.a(elfloader.c.o):source/elfloader.c:(.text+0x13b0): first defined here
/usr/local/ps4dev/libps4/lib/libps4.a(elfloader.c.o): In function `elfLoaderRelativeAddressIsExecutable':
source/ps4/elfloader.c:(.text+0x1250): multiple definition of`elfLoaderRelativeAddressIsExecutable'
/usr/local/ps4dev/libps4/lib/libps4link.a(elfloader.c.o):source/elfloader.c:(.text+0x1050): first defined here
/usr/local/ps4dev/libps4/lib/libps4.a(elfloader.c.o): In function `elfLoaderRelocate':
source/ps4/elfloader.c:(.text+0x1310): multiple definition of`elfLoaderRelocate'
/usr/local/ps4dev/libps4/lib/libps4link.a(elfloader.c.o):source/elfloader.c:(.text+0x1110): first defined here
/usr/local/ps4dev/libps4/lib/libps4.a(elfloader.c.o): In function `elfMemorySize':
source/ps4/elfloader.c:(.text+0x220): multiple definition of`elfMemorySize'
/usr/local/ps4dev/libps4/lib/libps4link.a(elfloader.c.o):source/elfloader.c:(.text+0x210): first defined here
/usr/local/ps4dev/libps4/lib/libps4.a(elfloader.c.o): In function `elfSection':
source/ps4/elfloader.c:(.text+0x3b0): multiple definition of`elfSection'
/usr/local/ps4dev/libps4/lib/libps4link.a(elfloader.c.o):source/elfloader.c:(.text+0x3c0): first defined here
/usr/local/ps4dev/libps4/lib/libps4.a(elfloader.c.o): In function `elfSectionAttribute':
source/ps4/elfloader.c:(.text+0x520): multiple definition of`elfSectionAttribute'
/usr/local/ps4dev/libps4/lib/libps4link.a(elfloader.c.o):source/elfloader.c:(.text+0x530): first defined here
/usr/local/ps4dev/libps4/lib/libps4.a(elfloader.c.o): In function `elfSectionByName':
source/ps4/elfloader.c:(.text+0x570): multiple definition of`elfSectionByName'
/usr/local/ps4dev/libps4/lib/libps4link.a(elfloader.c.o):source/elfloader.c:(.text+0x580): first defined here
/usr/local/ps4dev/libps4/lib/libps4.a(elfloader.c.o): In function `elfSectionStrings':
source/ps4/elfloader.c:(.text+0x350): multiple definition of`elfSectionStrings'
/usr/local/ps4dev/libps4/lib/libps4link.a(elfloader.c.o):source/elfloader.c:(.text+0x360): first defined here
/usr/local/ps4dev/libps4/lib/libps4.a(elfloader.c.o): In function `elfSections':
source/ps4/elfloader.c:(.text+0x310): multiple definition of`elfSections'
/usr/local/ps4dev/libps4/lib/libps4link.a(elfloader.c.o):source/elfloader.c:(.text+0x320): first defined here
/usr/local/ps4dev/libps4/lib/libps4.a(elfloader.c.o): In function `elfSegment':
source/ps4/elfloader.c:(.text+0xc0): multiple definition of`elfSegment'
/usr/local/ps4dev/libps4/lib/libps4link.a(elfloader.c.o):source/elfloader.c:(.text+0xb0): first defined here
/usr/local/ps4dev/libps4/lib/libps4.a(elfloader.c.o): In function `elfSegmentAttribute':
source/ps4/elfloader.c:(.text+0x680): multiple definition of`elfSegmentAttribute'
/usr/local/ps4dev/libps4/lib/libps4link.a(elfloader.c.o):source/elfloader.c:(.text+0x690): first defined here
/usr/local/ps4dev/libps4/lib/libps4.a(elfloader.c.o): In function `elfSegments':
source/ps4/elfloader.c:(.text+0x2d0): multiple definition of`elfSegments'
/usr/local/ps4dev/libps4/lib/libps4link.a(elfloader.c.o):source/elfloader.c:(.text+0x2e0): first defined here
/usr/local/ps4dev/libps4/lib/libps4.a(elfloader.c.o): In function `elfStringFromIndex':
source/ps4/elfloader.c:(.text+0xbe0): multiple definition of`elfStringFromIndex'
/usr/local/ps4dev/libps4/lib/libps4link.a(elfloader.c.o):source/elfloader.c:(.text+0x9e0): first defined here
/usr/local/ps4dev/libps4/lib/libps4.a(elfloader.c.o): In function `elfStringFromOffset':
source/ps4/elfloader.c:(.text+0xc30): multiple definition of`elfStringFromOffset'
/usr/local/ps4dev/libps4/lib/libps4link.a(elfloader.c.o):source/elfloader.c:(.text+0xa30): first defined here
/usr/local/ps4dev/libps4/lib/libps4.a(elfloader.c.o): In function `elfStringToIndex':
source/ps4/elfloader.c:(.text+0xc50): multiple definition of`elfStringToIndex'
/usr/local/ps4dev/libps4/lib/libps4link.a(elfloader.c.o):source/elfloader.c:(.text+0xa50): first defined here
/usr/local/ps4dev/libps4/lib/libps4.a(elfloader.c.o): In function `elfStringToOffset':
source/ps4/elfloader.c:(.text+0x630): multiple definition of`elfStringToOffset'
/usr/local/ps4dev/libps4/lib/libps4link.a(elfloader.c.o):source/elfloader.c:(.text+0x640): first defined here
/usr/local/ps4dev/libps4/lib/libps4.a(elfloader.c.o): In function `elfSymbolAttribute':
source/ps4/elfloader.c:(.text+0xdf0): multiple definition of`elfSymbolAttribute'
/usr/local/ps4dev/libps4/lib/libps4link.a(elfloader.c.o):source/elfloader.c:(.text+0xbf0): first defined here
/usr/local/ps4dev/libps4/lib/libps4.a(elfloader.c.o): In function `elfSymbols':
source/ps4/elfloader.c:(.text+0xe30): multiple definition of`elfSymbols'
/usr/local/ps4dev/libps4/lib/libps4link.a(elfloader.c.o):source/elfloader.c:(.text+0xc30): first defined here
/usr/local/ps4dev/libps4/lib/libps4link.a(commands.c.o): In function `ps4LinkRunElf':
source/commands.c:(.text+0x187): undefined reference to`ps4ProtectedMemoryWritable'
source/commands.c:(.text+0x19f): undefined reference to `ps4ProtectedMemoryExecutable'
source/commands.c:(.text+0x1dc): undefined reference to`ps4ProtectedMemoryWritable'
clang-3.9: error: linker command failed with exit code 1 (use -v to see invocation)
make: **\* [bin/ps4link.elf] Error 1

lib directory

drwxr-xr-x 2 user user    4096 apr 13 13:51 .
drwxrwxrwx 5 user user    4096 apr 13 13:44 ..
-rw-rw-r-- 1 user user    6048 apr 13 13:51 libdebugnet.a
-rw-r--r-- 1 user user 4112186 apr 13 13:44 libps4.a
-rw-rw-r-- 1 user user   55818 apr 13 15:24 libps4link.a

**Comment by hitodama** [comment]
Hi and apologies. I will from now on provide release tags, so that other peoples code does not break :)

I can currently not test this, but if I remember correctly you can probably do:
- In libps4link
  - remove source/elfloader.c
  - in source/command.c
    - replace all ps4ProtectedMemoryWritable with ps4ProtectedMemoryWritableAddress
    - replace all ps4ProtectedMemoryExecutable with ps4ProtectedMemoryExecutableAddress
  - make && make install

The rest should build as expected.

**Comment by psxdev** [comment]
Checkout last libps4 and last ps4link

Solved

**Comment by ghost** [comment]
If pulled the new sources and the previous error is solved, but now it gives me another linker error while generating bin/ldr

clang  /usr/local/ps4dev/libps4/crt0.s  build/commands.c.o  build/debugnet.c.o  build/main.c.o  build/ps4link.c.o  build/requests.c.o  -O3 -Wall -m64 -L. -Llib  -nostdlib -L/usr/local/ps4dev/libps4/lib -Wl,-Ttext,0x93a300000 -Wl,-Tdata,0x93a400000  -lps4 -o bin/ldr
/tmp/crt0-ffc2c1.o: In function `_start':
(.text+0x1): undefined reference to`_main'
/tmp/crt0-ffc2c1.o: In function `_start':
(.text+0x1): relocation truncated to fit: R_X86_64_PC32 against undefined symbol`_main'
clang-3.9: error: linker command failed with exit code 1 (use -v to see invocation)
make: **\* [bin/ldr] Error 1

Obviously main.c.o file exists in build directory and it does contain the main function. Any idea ?

**Comment by psxdev** [comment]
did you use a clean checkout for libps4 and ps4link? Please do it.

$ git clone http://github.com/psxdev/ps4link
Cloning into 'ps4link'...
remote: Counting objects: 180, done.
remote: Compressing objects: 100% (8/8), done.
remote: Total 180 (delta 0), reused 0 (delta 0), pack-reused 172
Receiving objects: 100% (180/180), 161.71 KiB | 0 bytes/s, done.
Resolving deltas: 100% (56/56), done.
Checking connectivity... done.
$ cd ps4link/
$ ls
LICENSE     elfldr      libps4link  ps4sh
README.md   libdebugnet ps4link     samples
$ cd elfldr/
$ ls
LICENSE local   ps4link
$ cd ps4link/
$ ls
Makefile        include         source
copy_ps4link_sources.sh ldrgen
$ sh copy_ps4link_sources.sh
$ gmake
clang37  -c source/ps4link.c -std=c11 -O3 -Wall -pedantic -m64 -mcmodel=large -I. -Iinclude  -ffreestanding -nostdlib -nostdinc -fno-builtin -D__PS4__ -I/usr/local/ps4dev/libps4/include -target x86_64-scei-ps4-elf -DPayload=0x926400000 -o build/ps4link.c.o
source/ps4link.c:58:5: warning: implicit declaration of function
      'ps4LinkCreateConf' is invalid in C99 [-Wimplicit-function-declaration]
        if(ps4LinkCreateConf())
           ^
source/ps4link.c:69:3: warning: implicit declaration of function 'sleep' is
      invalid in C99 [-Wimplicit-function-declaration]
                sleep(2);
                ^
source/ps4link.c:90:52: warning: incompatible pointer types passing
      'int (void _)' to parameter of type 'void *(_)(void _)'
      [-Wincompatible-pointer-types]
  ...NULL, ps4link_requests_thread, NULL, "ps4link_request_server_thread");
           ^~~~~~~~~~~~~~~~~~~~~~~
/usr/local/ps4dev/libps4/include/kernel.h:12:78: note: passing argument to
      parameter 'entry' here
  ..._thread, const ScePthreadAttr _attr, void *(_entry)(void _), void *arg, ...
                                                  ^
source/ps4link.c:106:52: warning: incompatible pointer types passing
      'int (void *)' to parameter of type 'void *(_)(void _)'
      [-Wincompatible-pointer-types]
  ...NULL, ps4link_commands_thread, NULL, "ps4link_command_server_thread");
           ^~~~~~~~~~~~~~~~~~~~~~~
/usr/local/ps4dev/libps4/include/kernel.h:12:78: note: passing argument to
      parameter 'entry' here
  ..._thread, const ScePthreadAttr _attr, void *(_entry)(void _), void *arg, ...
                                                  ^
4 warnings generated.
clang37  -c source/requests.c -std=c11 -O3 -Wall -pedantic -m64 -mcmodel=large -I. -Iinclude  -ffreestanding -nostdlib -nostdinc -fno-builtin -D__PS4__ -I/usr/local/ps4dev/libps4/include -target x86_64-scei-ps4-elf -DPayload=0x926400000 -o build/requests.c.o
source/requests.c:176:2: warning: implicit declaration of function 'strncpy' is
      invalid in C99 [-Wimplicit-function-declaration]
        strncpy(openreq->path, file, PS4LINK_MAX_PATH);
        ^
source/requests.c:255:11: warning: comparison of unsigned expression < 0 is
      always false [-Wtautological-compare]
        if (size < 0) {
            ~~~~ ^ ~
source/requests.c:285:61: warning: arithmetic on a pointer to void is a GNU
      extension [-Wpointer-arith]
  ...i = ps4link_recv_bytes(ps4LinkGetValue(FILEIO_SOCK), data+j_PACKET_MAXSI...
                                                          ~~~~^
source/requests.c:289:61: warning: arithmetic on a pointer to void is a GNU
      extension [-Wpointer-arith]
  ...i = ps4link_recv_bytes(ps4LinkGetValue(FILEIO_SOCK), data+j*PACKET_MAXSI...
                                                          ~~~~^
source/requests.c:350:3: warning: implicit declaration of function 'memcpy' is
      invalid in C99 [-Wimplicit-function-declaration]
                memcpy(&send_packet[sizeof(ps4link_pkt_write_req)], &dat...
                ^
source/requests.c:350:60: warning: subscript of a pointer to void is a GNU
      extension [-Wpointer-arith]
  ...memcpy(&send_packet[sizeof(ps4link_pkt_write_req)], &data[writtenbytes],...
                                                          ~~~~^
source/requests.c:640:2: warning: implicit declaration of function 'memset' is
      invalid in C99 [-Wimplicit-function-declaration]
        memset(serveraddr.sin_zero, 0, sizeof(serveraddr.sin_zero));
        ^
7 warnings generated.
clang37  -c source/commands.c -std=c11 -O3 -Wall -pedantic -m64 -mcmodel=large -I. -Iinclude  -ffreestanding -nostdlib -nostdinc -fno-builtin -D__PS4__ -I/usr/local/ps4dev/libps4/include -target x86_64-scei-ps4-elf -DPayload=0x926400000 -o build/commands.c.o
source/commands.c:56:6: warning: comparison of address of 'mm' equal to a null
      pointer is always false [-Wtautological-pointer-compare]
        if(&mm == NULL)
            ^~    ~~~~
source/commands.c:87:6: warning: comparison of address of 'mm' equal to a null
      pointer is always false [-Wtautological-pointer-compare]
        if(&mm ==  NULL)
            ^~     ~~~~
source/commands.c:251:6: warning: implicit declaration of function 'getuid' is
      invalid in C99 [-Wimplicit-function-declaration]
        UID=getuid();
            ^
source/commands.c:252:6: warning: implicit declaration of function 'getgid' is
      invalid in C99 [-Wimplicit-function-declaration]
        GID=getgid();
            ^
source/commands.c:265:30: warning: comparison of array 'pkg->argv' not equal to
      a null pointer is always true [-Wtautological-pointer-compare]
        if(UID==0 && GID==0 && pkg->argv!=NULL)
                               ~~~~~^~~~  ~~~~
source/commands.c:303:44: warning: arithmetic on a pointer to void is a GNU
      extension [-Wpointer-arith]
  ...dent = (struct dirent _)((void *)dent + dent->d_reclen);
                              ~~~~~~~~~~~~ ^
source/commands.c:314:7: warning: implicit declaration of function 'close' is
      invalid in C99 [-Wimplicit-function-declaration]
                err=close(dfd);
                    ^
source/commands.c:323:11: warning: comparison of array 'pkg->argv' not equal to
      a null pointer is always true [-Wtautological-pointer-compare]
                if(pkg->argv!=NULL)
                   ~~~~~^~~~  ~~~~
source/commands.c:372:5: warning: implicit declaration of function 'memset' is
      invalid in C99 [-Wimplicit-function-declaration]
    memset(&serveraddr, 0, sizeof serveraddr);
    ^
source/commands.c:408:108: warning: passing 'int *' to parameter of type
      'socklen_t *' (aka 'unsigned int *') converts between pointers to integer
      types with different sign [-Wpointer-sign]
  ...&recvbuf[0], BUF_SIZE, 0, (struct sockaddr *)&remote_addr,&addrlen);
                                                               ^~~~~~~~
/usr/local/ps4dev/libps4/include/sys/socket.h:615:96: note: passing argument to
      parameter here
  ..._, size_t, int, struct sockaddr \* **restrict, socklen_t \* __restrict);
                                                                         ^
10 warnings generated.
clang37  -c source/debugnet.c -std=c11 -O3 -Wall -pedantic -m64 -mcmodel=large -I. -Iinclude  -ffreestanding -nostdlib -nostdinc -fno-builtin -D__PS4** -I/usr/local/ps4dev/libps4/include -target x86_64-scei-ps4-elf -DPayload=0x926400000 -o build/debugnet.c.o
clang37  -c source/main.c -std=c11 -O3 -Wall -pedantic -m64 -mcmodel=large -I. -Iinclude  -ffreestanding -nostdlib -nostdinc -fno-builtin -D__PS4__ -I/usr/local/ps4dev/libps4/include -target x86_64-scei-ps4-elf -DPayload=0x926400000 -o build/main.c.o
clang37  /usr/local/ps4dev/libps4/crt0.s  build/ps4link.c.o  build/requests.c.o  build/commands.c.o  build/debugnet.c.o  build/main.c.o  -O3 -Wall -m64 -L. -Llib  -nostdlib -L/usr/local/ps4dev/libps4/lib -Wl,-Ttext,0x93a300000 -Wl,-Tdata,0x93a400000  -lps4 -o bin/ldr
objcopy bin/ldr -O binary bin/ldr
clang37 ldrgen/main.c ldrgen/util.c -std=c11 -O3 -Wall -pedantic -Iinclude -o bin/ldrgen
bin/ldrgen Elf bin/ldr ../local/ldr/ldr.js
Generated Elf in ../local/ldr/ldr.js from bin bin/ldr

check if you are not updated crt0

cat /usr/local/ps4dev/libps4/crt0.s
.pushsection .text
.global _start
.type _start, @function
_start:
    jmp main
.size _start, .-_start
.popsection

**Comment by ghost** [comment]
I had a bad crt0.s :( It gave me another error while compiling ldrgen, it seems a bad include flag -I (does not look in /usr/local/ps4dev/libps4/include, only local include folder), however I managed to compile ldrgen manually (I am using make, not gmake I do not know if this could be the problem)...at the end everything ok thanks

```
clang ldrgen/main.c ldrgen/util.c -std=c11 -O3 -Wall -pedantic -Iinclude -o bin/ldrgen
In file included from ldrgen/main.c:1:
In file included from /usr/include/stdlib.h:24:
/usr/include/features.h:374:12: fatal error: 'sys/cdefs.h' file not found
#  include <sys/cdefs.h>
           ^
1 error generated.
make: *** [bin/ldrgen] Error 1
```

**Comment by psxdev** [comment]
ok closing issue then
