### ISSUE TITLE
freeBSD error when try to compile elfldr

### ISSUE THREAD

**Issue by eth-man** [psxdev/ps4link#5]
# export

declare -x BLOCKSIZE="K"
declare -x COMPILER="clang38"
declare -x EDITOR="vim"
declare -x ENV="/root/.shrc"
declare -x HOME="/root"
declare -x LOGNAME="root"
declare -x MAIL="/var/mail/root"
declare -x OLDPWD="/usr/local/ps4dev/git/ps4link/elfldr/ps4link/ldrgen"
declare -x PAGER="more"
declare -x PATH="/sbin:/bin:/usr/sbin:/usr/bin:/usr/local/sbin:/usr/local/bin:/root/bin"
declare -x PS4DEV="/usr/local/ps4dev"
declare -x PWD="/usr/local/ps4dev/git/ps4link/elfldr/ps4link"
declare -x SHELL="/usr/local/bin/bash"
declare -x SHLVL="1"
declare -x SSH_CLIENT="192.168.1.17 55917 22"
declare -x SSH_CONNECTION="192.168.1.17 55917 192.168.1.22 22"
declare -x SSH_TTY="/dev/pts/0"
declare -x TERM="linux"
declare -x USER="root"
declare -x libps4="/usr/local/ps4dev/libps4"
# clang -v

FreeBSD clang version 3.8.0 (tags/RELEASE_380/final 262564) (based on LLVM 3.8.0)
Target: x86_64-unknown-freebsd11.0
Thread model: posix
InstalledDir: /usr/bin
# gmake

clang  -c source/ps4link.c -std=c11 -O3 -Wall -pedantic -m64 -mcmodel=large -I. -Iinclude  -ffreestanding -nostdlib -nostdinc -fno-builtin -D__PS4__ -I/usr/local/ps4dev/libps4/include -target x86_64-scei-ps4-elf -DPayload=0x926400000 -o build/ps4link.c.o
source/ps4link.c:58:5: warning: implicit declaration of function 'ps4LinkCreateConf' is invalid in C99 [-Wimplicit-function-declaration]
        if(ps4LinkCreateConf())
           ^
source/ps4link.c:69:3: warning: implicit declaration of function 'sleep' is invalid in C99 [-Wimplicit-function-declaration]
                sleep(2);
                ^
source/ps4link.c:90:52: warning: incompatible pointer types passing 'int (void _)' to parameter of type 'void *(_)(void _)' [-Wincompatible-pointer-types]
                ret=scePthreadCreate(&server_request_thid, NULL, ps4link_requests_thread, NULL, "ps4link_request_server_thread");
                                                                 ^~~~~~~~~~~~~~~~~~~~~~~
/usr/local/ps4dev/libps4/include/kernel.h:12:78: note: passing argument to parameter 'entry' here
int scePthreadCreate(ScePthread *thread, const ScePthreadAttr *attr, void *(_entry)(void _), void *arg, const char *name);
                                                                             ^
source/ps4link.c:106:52: warning: incompatible pointer types passing 'int (void *)' to parameter of type 'void *(_)(void _)' [-Wincompatible-pointer-types]
                ret=scePthreadCreate(&server_command_thid, NULL, ps4link_commands_thread, NULL, "ps4link_command_server_thread");
                                                                 ^~~~~~~~~~~~~~~~~~~~~~~
/usr/local/ps4dev/libps4/include/kernel.h:12:78: note: passing argument to parameter 'entry' here
int scePthreadCreate(ScePthread *thread, const ScePthreadAttr *attr, void *(_entry)(void _), void *arg, const char *name);
                                                                             ^
4 warnings generated.
clang  -c source/requests.c -std=c11 -O3 -Wall -pedantic -m64 -mcmodel=large -I. -Iinclude  -ffreestanding -nostdlib -nostdinc -fno-builtin -D__PS4__ -I/usr/local/ps4dev/libps4/include -target x86_64-scei-ps4-elf -DPayload=0x926400000 -o build/requests.c.o
source/requests.c:176:2: warning: implicit declaration of function 'strncpy' is invalid in C99 [-Wimplicit-function-declaration]
        strncpy(openreq->path, file, PS4LINK_MAX_PATH);
        ^
source/requests.c:255:11: warning: comparison of unsigned expression < 0 is always false [-Wtautological-compare]
        if (size < 0) {
            ~~~~ ^ ~
source/requests.c:285:61: warning: arithmetic on a pointer to void is a GNU extension [-Wpointer-arith]
                        i = ps4link_recv_bytes(ps4LinkGetValue(FILEIO_SOCK), data+j_PACKET_MAXSIZE, PACKET_MAXSIZE);
                                                                             ~~~~^
source/requests.c:289:61: warning: arithmetic on a pointer to void is a GNU extension [-Wpointer-arith]
                        i = ps4link_recv_bytes(ps4LinkGetValue(FILEIO_SOCK), data+j*PACKET_MAXSIZE, PACKET_MAXSIZE+lastread);
                                                                             ~~~~^
source/requests.c:350:3: warning: implicit declaration of function 'memcpy' is invalid in C99 [-Wimplicit-function-declaration]
                memcpy(&send_packet[sizeof(ps4link_pkt_write_req)], &data[writtenbytes],nbytes);
                ^
source/requests.c:350:60: warning: subscript of a pointer to void is a GNU extension [-Wpointer-arith]
                memcpy(&send_packet[sizeof(ps4link_pkt_write_req)], &data[writtenbytes],nbytes);
                                                                     ~~~~^
source/requests.c:640:2: warning: implicit declaration of function 'memset' is invalid in C99 [-Wimplicit-function-declaration]
        memset(serveraddr.sin_zero, 0, sizeof(serveraddr.sin_zero));
        ^
7 warnings generated.
clang  -c source/commands.c -std=c11 -O3 -Wall -pedantic -m64 -mcmodel=large -I. -Iinclude  -ffreestanding -nostdlib -nostdinc -fno-builtin -D__PS4__ -I/usr/local/ps4dev/libps4/include -target x86_64-scei-ps4-elf -DPayload=0x926400000 -o build/commands.c.o
source/commands.c:56:6: warning: comparison of address of 'mm' equal to a null pointer is always false [-Wtautological-pointer-compare]
        if(&mm == NULL)
            ^~    ~~~~
source/commands.c:87:6: warning: comparison of address of 'mm' equal to a null pointer is always false [-Wtautological-pointer-compare]
        if(&mm ==  NULL)
            ^~     ~~~~
source/commands.c:251:6: warning: implicit declaration of function 'getuid' is invalid in C99 [-Wimplicit-function-declaration]
        UID=getuid();
            ^
source/commands.c:252:6: warning: implicit declaration of function 'getgid' is invalid in C99 [-Wimplicit-function-declaration]
        GID=getgid();
            ^
source/commands.c:265:30: warning: comparison of array 'pkg->argv' not equal to a null pointer is always true [-Wtautological-pointer-compare]
        if(UID==0 && GID==0 && pkg->argv!=NULL)
                               ~~~~~^~~~  ~~~~
source/commands.c:303:44: warning: arithmetic on a pointer to void is a GNU extension [-Wpointer-arith]
                                        dent = (struct dirent _)((void *)dent + dent->d_reclen);
                                                                 ~~~~~~~~~~~~ ^
source/commands.c:314:7: warning: implicit declaration of function 'close' is invalid in C99 [-Wimplicit-function-declaration]
                err=close(dfd);  
                    ^
source/commands.c:323:11: warning: comparison of array 'pkg->argv' not equal to a null pointer is always true [-Wtautological-pointer-compare]
                if(pkg->argv!=NULL)
                   ~~~~~^~~~  ~~~~
source/commands.c:372:5: warning: implicit declaration of function 'memset' is invalid in C99 [-Wimplicit-function-declaration]
    memset(&serveraddr, 0, sizeof serveraddr);
    ^
source/commands.c:408:108: warning: passing 'int *' to parameter of type 'socklen_t *' (aka 'unsigned int *') converts between pointers to integer types with different sign [-Wpointer-sign]
                len = recvfrom(ps4LinkGetValue(COMMANDS_SOCK), &recvbuf[0], BUF_SIZE, 0, (struct sockaddr *)&remote_addr,&addrlen);
                                                                                                                         ^~~~~~~~
/usr/local/ps4dev/libps4/include/sys/socket.h:615:96: note: passing argument to parameter here
ssize_t recvfrom(int, void *, size_t, int, struct sockaddr \* **restrict, socklen_t \* __restrict);
                                                                                               ^
10 warnings generated.
clang  -c source/debugnet.c -std=c11 -O3 -Wall -pedantic -m64 -mcmodel=large -I. -Iinclude  -ffreestanding -nostdlib -nostdinc -fno-builtin -D__PS4** -I/usr/local/ps4dev/libps4/include -target x86_64-scei-ps4-elf -DPayload=0x926400000 -o build/debugnet.c.o
clang  -c source/elfloader.c -std=c11 -O3 -Wall -pedantic -m64 -mcmodel=large -I. -Iinclude  -ffreestanding -nostdlib -nostdinc -fno-builtin -D__PS4__ -I/usr/local/ps4dev/libps4/include -target x86_64-scei-ps4-elf -DPayload=0x926400000 -o build/elfloader.c.o
clang  -c source/main.c -std=c11 -O3 -Wall -pedantic -m64 -mcmodel=large -I. -Iinclude  -ffreestanding -nostdlib -nostdinc -fno-builtin -D__PS4__ -I/usr/local/ps4dev/libps4/include -target x86_64-scei-ps4-elf -DPayload=0x926400000 -o build/main.c.o
clang  /usr/local/ps4dev/libps4/crt0.s  build/ps4link.c.o  build/requests.c.o  build/commands.c.o  build/debugnet.c.o  build/elfloader.c.o  build/main.c.o  -O3 -Wall -m64 -L. -Llib  -nostdlib -L/usr/local/ps4dev/libps4/lib -Wl,--build-id=none -Wl,-Ttext,0x926200000 -Wl,-Tdata,0x926300000  -lps4 -o bin/ldr
/usr/bin/ld: unrecognized option '--build-id=none'
/usr/bin/ld: use the --help option for usage information
clang: error: linker command failed with exit code 1 (use -v to see invocation)
/usr/local/ps4dev/libps4/make//targets/ps4-bin.mk:33: recipe for target 'bin/ldr' failed
gmake: *_\* [bin/ldr] Error 1

this is frustrating ,what im missing here? 
hope you guys can help me to compile this

**Comment by psxdev** [comment]
checkout last libps4 from ps4dev and last ps4link. Your problem must be solve.

Please confirm

**Comment by eth-man** [comment]
nice, still got some warnings but im able to compile now!
